# List of zookeeper servers
servers:
  - server: "test:2181"     #host:port
    serverId: 1
    displayName: zk1
  - server: "test:2182"
    serverId: 2
    displayName: zk2
  - server: "test:2183"
    serverId: 3
    displayName: zk3
  - server: "test:2184"
    serverId: 4
    displayName: zk4
  - server: "test:2185"
    serverId: 5
    displayName: zk5

# The list of commands can be found here http://zookeeper.apache.org/doc/r3.4.6/zookeeperAdmin.html#sc_zkCommands

commands:
   - command: "ruok"
   - command: "stat"
     separator: ":"
     fields: [
        Received,
        Sent,
        Outstanding,
        Node count
        #Latency min/avg/max
     ]

# Uncomment the following to support additional metrics
   - command: "mntr"
     separator: "\t"
     fields: [
       zk_avg_latency,
       zk_max_latency,
       zk_min_latency,
       zk_packets_received,
       zk_packets_sent,
       zk_num_alive_connections,
       zk_outstanding_requests,
       zk_znode_count,
       zk_watch_count,
       zk_ephemerals_count,
       zk_approximate_data_size,
       zk_followers,                      #only exposed by the Leader
       zk_synced_followers,               #only exposed by the Leader
       zk_pending_syncs,                  #only exposed by the Leader
       zk_open_file_descriptor_count,     #only available on Unix platforms
       zk_max_file_descriptor_count       #only available on Unix platforms
     ]


#prefix used to show up metrics in AppDynamics
metricPrefix:  "Zookeeper"

# number of concurrent tasks
numberOfThreads: 5

#timeout for the thread
threadTimeout: 60

pollingInterval: 60

#Gmond host
gmondHost: test
gmondPort: 8649